[package]
name = "fluff-gui"
version = "0.1.0"
edition = "2024"

[dependencies]
kyute = { workspace = true }
tracing = "0.1.40"
bitflags = "2.6.0"

[dev-dependencies]
tracing-subscriber = { version = "0.3.10", features = ["fmt", "env-filter"] }
tracing-tree = "0.4"